### ISSUE TITLE
Compass Too Precise

### ISSUE THREAD

**Issue by enusbaum** [asmcup/runtime#127]
I was working on a patch locally but wanted to get folks opinion on this. 

Currently the compass returns a full float with several decimal places of precision. The use cases I've found for the compass thus far and how those solutions have worked:

**Which direction am I facing**
Been able to compare if_gtf and if_ltf known coordinates for "north", "south", etc. Seems to work alright.

**Which direction am I facing so I can return to that direction after turning or "scanning"**
This has been a problem. Because of the decimal precision returned from the compass, the best I could come up with is divide my current position by the known previous position and see the % difference and try and stop within a known % of that point. The issue is the robot turning at even 0.2 will probably blow past the EXACT point previously captured.

So I'm thinking this could be fixed two ways:

**Easy Fix**
Lower decimal precision of compass to 2 decimal places. This should be a better "approximation" of direction and allow people a better opportunity to be able to return to a known direction while turning.

**Harder Fix**
Refactor the compass to return the bot direction in 360-degree value. with 0 being "North", 90 being "East" and so on. With no decimal notation and known, common coordinates, it would be much easier to orient the bot.

Thoughts?

**Comment by MLanghof** [comment]
I understand your problem (making robot face a certain direction), but I don't understand how lowering the compass precision would be of any help. How do the 3rd and 4th etc. digit make your life harder?

**Comment by enusbaum** [comment]
The pseudocode for what would be done to determine if I've done a 360 would be:

```
get current compass position
begin turning
read compass position
if original position: stop
continue reading
```

The current implementation will return a float with the value +0.53407085

The odds of me returning to EXACTLY that point, even turning 0.01 and running the CPU at 100 for overclock are very slim. This is partially because the robot continues turning while instructions are being processed.

Lowering the precision makes the arc angles larger. So right now there several million "points" which will be returned from the compass. Lowering the precision takes us closer to a practical implementation of "360 degrees".

This is the best code I've been able to come up with to determine if I've returned to the same point:

```
direction_check:
push8 #IO_COMPASS
io
pushf _start
subf
absf
pushf 0.05
if_ltef
jnz direction_check
```

If I were sampling the compass millions of times per second, than this precision would make sense.

Again, thats why previous post was saying is lowering the precision to 360 degrees gives us a greater probability of evaluating each degree of change in a loop if turning at a reasonable rate and at a reasonable overclock. But short of full rounded 360-degrees, lowering the precision of the current decimal might work just as well.

**Comment by SiebelsTim** [comment]
The usual approach would be not to check for equality (which is bad for floating point numbers anyway). One should check with a delta

```
abs(x - y) < 0.00001f
```

However, I agree that this increases code size very much.

I would rather go for an instruction that does exactly that, opposed to lowering precision (which in the end won't resolve such issues anyway).

**Comment by enusbaum** [comment]
My original concern is even with the check for delta being: 

```
abs(x - y) < 0.00001f
```

The value you're comparing against depends on how fast your instructions are processing and how fast you're turning. In the case of a 20 IPS overclock and a turn rate of 0.2, the best you would be able to check against with relative accuracy might be 0.1 which again gives a fairly broad arc angle for accuracy.

**Comment by enusbaum** [comment]
Also it appears that the compass values are the same for angles 180 degrees opposite. Which makes it of limited value for identifying a point in space.

**Comment by MLanghof** [comment]
You should never compare floating point numbers for equality. Not in asmcup and not in any other code.

In this case, reducing the float accuracy would be unlikely to improve the situation, even if your approach was acceptable.

If you are turning to reach an orientation, you must be turning into a certain direction. Since you know that direction, you know if your facing angle should increase or decrease. Given this, you can just check if it became larger/smaller (depending on turning direction) than the facing angle you want to reach.

**Comment by enusbaum** [comment]
> You should never compare floating point numbers for equality. Not in asmcup and not in any other code.

Not what I was implying and if that was how my example I came across it wasn't my intention.

I think, to rephrase, what I was originally getting at, is the example provided: 

```
abs(x - y) < 0.00001f
```

This example assumes you're sampling and turning at a rate that you will be within 0.00001f in delta between two reads of the compass while turning. My original point is due to latency while executing instructions and given turning speed, the odds of that equating to true are very, very small.

So to make the area of the above equating to true larger and more likely to evaluate true, you have to make the arc angles larger by:
1. Reduce the accuracy of the compass (round up to 2 decimal places) thus lowering the measurable degrees in the angle (where I think 360 is realistic and of use)
2. Mathematically widen your window for accuracy of the compass for the above example by modifying it to:

```
abs(x - y) < 0.01f
```

My intention here is to make the compass useful. Being able to locate a point and return to it is, in my mind, the primary function of the compass.

**Comment by MLanghof** [comment]
But the problem is not the compass. The problem is the limited temporal resolution of the robot turning. Reducing compass precision doesn't help the issue. If the compass returned angles in 90° steps, it wouldn't make turning back to the same point any easier!

And my solution still stands: Just check for `x >= y` (or `x <= y` if you're turning the other way).

I concur that the compass should have 360° range, not 180°. I'll probably PR that soon-ish.

**Comment by enusbaum** [comment]
Agreed

I think there's something to be said here for balance in that if you want a bot thats smart about direction, then you'll have to sacrifice program space. So I'm not terribly put out that the extra instructions are required.

My primary concern was around just the accuracy and the usability of the compass as provided.

**Comment by MLanghof** [comment]
Oh, were you saying that 360 (integer) degrees would be better because you wouldn't have to do floating point math, thereby saving program size? (This can't work because our "integers" are bytes with only 256 different values).

If you actually mean that there should only be 360 distinguishable compass values... I still don't understand how that helps. You still shouldn't check for float equality, so the only thing you can do is compare the floats for which one is larger. And if you do that, higher compass accuracy _helps_ you turn more precisely (how would you turn to face 34° if your compass only tells you N/S/W/E?).

**Comment by krisives** [comment]
I have been a bit busy with other parts of the competition the last few days, but I have been monitoring this issue via email.

Do you think the changes @MLanghof made to have the compass range from 0 - 2PI give you the tools needed to do this?

**Comment by enusbaum** [comment]
I'll give it a whirl.

The more I gave it some thought, you don't want to make this function TOO easy. There should be a trade off if you're looking to have a smarter bot then you'll have to sacrifice memory.

**Comment by krisives** [comment]
Feel free to re-open anytime.
