### ISSUE TITLE
Evaluator intricacies

### ISSUE THREAD

**Issue by MLanghof** [asmcup/runtime#149]
The score values that come out of the evaluator are currently not easily interpretable. That's fine for the GA, they only need to relate to each other, but from the "user bot evaluator" perspective there are some things in there that may be confusing.

- The `calculate360()` function scores 8 different angles. This is both arbitrary and not obvious. I'm not sure what the advantage of this is, given that scoring a completely new world instead would cost virtually the same computational resources while eliminating the redundancy associated with having the same starting point. I'd vote for removing it.

- There's a 0.001 score benefit each tick for being alive. I'm aware that this amounts to only 36 additional score over an hour (!) of normal game time while helping the GA through a sense of direction, I don't want to remove it, but it might be confusing to get a positive score when setting all scoring metrics to zero...

- Should we maybe take an average of all scores? The GA wouldn't care, but the result is much more immediately useful for users evaluating their own code.

**Comment by krisives** [comment]
> The calculate360() function scores 8 different angles. This is both arbitrary and not obvious. I'm not sure what the advantage of this is, given that scoring a completely new world instead would cost virtually the same computational resources while eliminating the redundancy associated with having the same starting point. I'd vote for removing it.

Assuming it's implemented the way I last had it (which it appears it is) it should actually be scoring the same world in 8 different directions. This helps a bot learn how to avoid walls or death hazards by placing them near them without overfitting. Without it a bot will just reverse away or develop some "magic driving" to avoid the wall instead of learning how to use the sensor, or you have to manually place your bot in various rotations to simulate it. 

> There's a 0.001 score benefit each tick for being alive

My experience with this is that giving it some hill to climb helps it develop "scalable strategies" in particular when force training a bot to have valid stack/IO. I picked a number that was small so that some hill would exist while trying not to bias other actions like exploring or collecting gold etc.

> Should we maybe take an average of all scores? The GA wouldn't care, but the result is much more immediately useful for users evaluating their own code.

I'm not sure there is any meaningful way to represent a number with so much information mixed into it.

**Comment by MLanghof** [comment]
> Without it a bot will just reverse away or develop some "magic driving" to avoid the wall instead of learning how to use the sensor, or you have to manually place your bot in various rotations to simulate it. 

Oh right, I completely forgot about the fact that this also applies to spawns, not only random worlds. Can't argue with you there. Do you see my point for random worlds though?

> I'm not sure there is any meaningful way to represent a number with so much information mixed into it.

If I set the evaluator to only reward gold collection (i.e. mimic the actual contest), it's a pretty meaningful number...
