### ISSUE TITLE
Compass Enhancment

### ISSUE THREAD

**Issue by enusbaum** [asmcup/runtime#79]
I think it would be helpful to have a compass IO in order to determine orientation in relation to the world.

An example is that it would pop a float to the stack with 0-359 which would represent the direction the sensor is facing. 0 being straight "north" on the map, 90 being "east", 180 being "south" and 270 being "west".

**Comment by krisives** [comment]
This is something we have been talking about to reduce the amount of spinning needed. The idea is IO_SENSOR_CONFIG or a new IO command. What do you think?

**Comment by enusbaum** [comment]
I see it as either an additional field as part of the accelerometer or as its own sensor.

I like it as its own new IO as it'd be a single float to the stack versus adding another float in addition to the accelerometer fields.

**Comment by krisives** [comment]
Oh I see so similar to IO_ACCELEROMETER we can have something like IO_GPS or IO_COMPASS which gives them a more general view of their position in the world.

**Comment by enusbaum** [comment]
Exactly! I think this would be a huge help in making the bots a lot smarter while not having to futz around with calculating turning speed / clock etc. etc.

**Comment by MLanghof** [comment]
I'd like to remark that "accelerometer" is a confusing name for something that returns distance traveled. I guess it's a remnant from earlier when IO_MOTOR and IO_STEER would actually accelerate instead of just setting velocities. Regardless, we should consider changing the name to something more meaningful (or just straight up replacing it by IO_GPS and/or IO_COMPASS).

**Comment by enusbaum** [comment]
Well, this is where I was mentioning that the documentation around the accelerometer is a bit lacking. It looks like it's returning X/Y relative to the map, not relative to the bot.

And to your point, it's not measuring acceleration force but it's more of an odometer for X/Y.

**Comment by SiebelsTim** [comment]
@enusbaum According to the code, it would return relative position after the second read to that. 
Anyway, that a bug proposed to be fixed in #82

**Comment by enusbaum** [comment]
Thanks!

Also, I think the recommendations by @MLanghof IO_GPS for map location Y/X and IO_COMPASS for robot direction would be all anyone would need. From that they could work their own acceleration/distance traveled calculations.

**Comment by krisives** [comment]
@MLanghof  It's called an accelerometer because that's what the "real life" sensor equivalent is, at least to the best of my knowledge. Your phone has a small accelerometer and uses two of them on different axis to determine the rotation and movement. I have toyed with a few on my Arduino in the past.

**Comment by krisives** [comment]
@enusbaum IO_ACCELEROMETER (minus a bug we had) should return the change in X/Y position since the last time IO_ACCELEROMETER was used allowing for relative position tracking. I updated the documentation in one of my pull requests to reflect this.

Any of this behavior could be changed I'm just trying to help make it clear how things work, what is expected, etc.

**Comment by MLanghof** [comment]
I agree that there are sensors able to estimate a displacement by integrating the values of an accelerometer over time, and that they often inherit the name, but strictly speaking an accelerometer does just that, measuring acceleration.

Regardless of semantics, is anybody opposed to replacing IO_ACCELEROMETER by IO_GPS and IO_COMPASS?

**Comment by enusbaum** [comment]
I think there's value in the three. 

IO_ACCELEROMETER -- Distance Traveled since last poll
IO_GPS -- Current map X/Y
IO_COMPASS -- Current bot orientation in relation to map (360-degrees, 0 North)

**Comment by krisives** [comment]
Okay, tons of stuff here, thanks to everyone for chiming in. Firstly, I mentioned IO_GPS but my goal wasn't to give out absolute X/Y positions of robots. I don't want to give out the absolute positions of robots because that's not very close to real robotics programming in my experience. One of the challenges of making a robot in real life is having it become aware of it's surroundings and I don't want to remove that from the game.

I didn't explain it clearly before but the reason I implemented IO_COMPASS the way I did originally was to attempt to satisfy both needs of finding out your orientation and your general global position.  It didn't work so great and that's why I have changed it to simply return the "facing" direction of the robot.

I'm open to ideas on how a bot could determine their positions relative to one another or do some form of triangulation (which is how real GPS works) but I don't want to simply expose raw coordinates.

Cheers & Thanks to everyone for helping!

**Comment by MLanghof** [comment]
So to recap, we'll probably roll with IO_ACCELEROMETER (x/y distance traveled) + IO_COMPASS (global facing). This shouldn't allow access to global coordinates, but retains usefulness for programmers.

One way bots might _technically_ find out their (rough) global position is by looking at the spacing of float distance values (from accelerometer) when driving very slowly. The different ULPs at different coordinates (as in, when they differ by order of magnitude) can tell a thing or two about where you are. It's not even very hard to implement, but I don't see much use in it.

**Comment by SiebelsTim** [comment]
> Okay, tons of stuff here, thanks to everyone for chiming in. Firstly, I mentioned IO_GPS but my goal wasn't to give out absolute X/Y positions of robots. I don't want to give out the absolute positions of robots because that's not very close to real robotics programming in my experience. One of the challenges of making a robot in real life is having it become aware of it's surroundings and I don't want to remove that from the game.

Exactly my train of thought. The robots are limited to 256B of ram, but can read out gps? That sounds weird.

**Comment by krisives** [comment]
This was merged and we now have IO_COMPASS I will bump versions and make a release!
